### PR TITLE
Added autosolve

### PR DESCRIPTION
**Pull request by ligio90**
Ok

### CODE REVIEW

**Review by marksam32 — COMMENTED** [review]
No, you suck at coding

**Comment by ligio90** [comment]
Self sex

**Review by ligio90 — COMMENTED** [review]
code LGTM

**Comment by ligio90** [comment]
Cyrill_Demon

**Comment by marksam32** [comment]
This code looks like my cat's poophole

**Comment by marksam32** [comment]
Pls fix code before merge

**Comment by marksam32** [comment]
Looking good, I have reviewed your changes and I don't see anything too bad. However, you are using short. Which makes me pissed. However, since I am nice, I will merge 👎

**Pull request merged**
